### ISSUE TITLE
Support batching in 1.6 driver

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool-python#55]

**Comment by buriy** [comment]
would like to have batching support in the client.

**Comment by ichuev** [comment]
Yes, something to reduce round-trips from client to database would certainly be a great feature.

**Comment by bofm** [comment]
A dirty workaround might help for now. Here is a batch insert variant.
```
from itertools import islice

def load_tarantool(t, items, space_name):
    space_sid = t.schema.get_space(space_name).sid
    items = iter(items)
    chunk_size = 1000
    chunk = tuple(islice(items, chunk_size))
    n = 0
    while chunk:
        payload = b''.join(bytes(RequestInsert(t, space_sid, item)) for item in chunk)
        t._socket.sendall(payload)
        try:
            assert all(Response(t, t._read_response()) for _ in chunk)
        except SchemaReloadException as e:
            t.update_schema(e.schema_version)
            continue
        n += len(chunk)
        chunk = tuple(islice(items, chunk_size))
    print(f'inserted {n} items') 
```

**Comment by DifferentialOrange** [comment]
There is no any native support for batching in basic IPROTO requests. Just sending a sequence of inserts isn't nice since some of them may fail in the middle and we won't have any possibility to handle it properly.

On the other hand, `crud` module has `*_many` methods which is essentially a batch insert/replace/upsert for sharded systems. These handles will be supported as part of the https://github.com/tarantool/tarantool-python/issues/205 issue. So I'm closing this one in favor of https://github.com/tarantool/tarantool-python/issues/205
